#theme: jekyll-theme-minimal
title: Hua Wu's Homepage
main:
  - title: "Publications"
    url: /publications/

  - title: "Talks"
    url: /talks/    
    
  - title: "Portfolio"
    url: /portfolio/
    
  - title: "CV"
    url: /cv/
    
